---
version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_java_test
    restart: always
    ports:
      - '6700:5432'
    environment:
      PGUSER: user
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres